import { passkey } from '@better-auth/passkey'
import { betterAuth } from 'better-auth'
import { drizzleAdapter } from 'better-auth/adapters/drizzle'
import { tanstackStartCookies } from 'better-auth/tanstack-start/solid'
import { z } from 'zod'
import {
  consumeRecoveryLink,
  createAccount,
  getAccountByEmail,
  getAccountById,
} from './db/accounts'
import { getDb } from './db/client'
import * as schema from './db/schema'

/**
 * Two contexts travel in the passkey registration ceremony's `context` field:
 * - signup: first-time enrollment (no session); carries the user's email+name.
 * - recovery: break-glass re-enrollment; carries a single-use recovery token
 *   generated by an organizer. The token is consumed here, atomically with the
 *   passkey being added, so it cannot be reused.
 */
const signupContextSchema = z.object({
  type: z.literal('signup'),
  email: z.email(),
  name: z.string().min(1),
})

const recoveryContextSchema = z.object({
  type: z.literal('recovery'),
  token: z.string().min(1),
})

const registrationContextSchema = z.discriminatedUnion('type', [
  signupContextSchema,
  recoveryContextSchema,
])

/**
 * Parse ORGANIZER_EMAIL_ALLOWLIST into a Set of lower-cased emails.
 * Empty string / undefined → empty Set (no one gets the organizer role by env).
 */
function parseAllowlist(raw: string | undefined): ReadonlySet<string> {
  if (!raw) return new Set()
  return new Set(
    raw
      .split(',')
      .map((e) => e.trim().toLowerCase())
      .filter(Boolean),
  )
}

function buildAuth(
  db: Awaited<ReturnType<typeof getDb>>,
  env: {
    BETTER_AUTH_URL?: string
    BETTER_AUTH_SECRET?: string
    PASSKEY_RP_ID?: string
    ORGANIZER_EMAIL_ALLOWLIST?: string
  },
) {
  const organizerAllowlist = parseAllowlist(env.ORGANIZER_EMAIL_ALLOWLIST)

  return betterAuth({
    baseURL: env.BETTER_AUTH_URL,
    secret: env.BETTER_AUTH_SECRET,
    database: drizzleAdapter(db, { provider: 'pg', schema }),
    // No email is sent anywhere in this app (see authentication ADR); email is
    // stored as contact info + the identifier a passkey binds to.
    emailAndPassword: { enabled: false },
    plugins: [
      passkey({
        rpID: env.PASSKEY_RP_ID ?? 'localhost',
        rpName: 'WRO Denmark',
        origin: env.BETTER_AUTH_URL ?? 'http://localhost:3000',
        registration: {
          // Passkey-first: a visitor enrolls a passkey with no prior session.
          requireSession: false,
          resolveUser: async ({ context }) => {
            const parsed = registrationContextSchema.parse(
              JSON.parse(context || '{}'),
            )

            if (parsed.type === 'recovery') {
              // Break-glass flow: consume the single-use token (throws if
              // invalid, expired, or already used) and return the locked-out
              // coach's Account so the new passkey binds to it.
              const targetUserId = await consumeRecoveryLink(db, parsed.token)
              const account = await getAccountById(db, targetUserId)
              if (!account) throw new Error('Recovery target account not found')
              return account
            }

            // Normal signup flow
            const { email, name } = parsed
            const existing = await getAccountByEmail(db, email)
            if (existing) return existing
            const role = organizerAllowlist.has(email.toLowerCase())
              ? 'organizer'
              : 'coach'
            return createAccount(db, { email, name, role })
          },
        },
      }),
      // Must stay last: wires cookie writes into TanStack Start's system.
      tanstackStartCookies(),
    ],
  })
}

type AuthInstance = ReturnType<typeof buildAuth>

let cached: AuthInstance | undefined

/**
 * Build (once) the Better Auth instance. Kept lazy so importing this module
 * never touches `DATABASE_URL` or opens a connection — the auth/dashboard
 * routes are excluded from prerender, and this must not run during the build.
 */
export async function getAuth(): Promise<AuthInstance> {
  if (cached) {
    return cached
  }

  const [db, { env }] = await Promise.all([getDb(), import('~/env')])
  cached = buildAuth(db, env)
  return cached
}
