/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: npm run images:generate
 * Source: assets/images/
 * Output: public/images/
 */

/**
 * Per-image actual output widths.
 * Widths reflect the real pixel width of each generated file — sources narrower
 * than a breakpoint produce a smaller file named after the target breakpoint but
 * with the actual (not the target) width recorded here for correct srcset descriptors.
 */
export const IMAGE_MANIFEST = {
  carousel: {
    'abu-dhabi-1': [640, 1024, 1280, 1920],
    'abu-dhabi-2': [640, 1024, 1280, 1920],
  },
} as const

/** Available image folder names */
export type ImageFolder = keyof typeof IMAGE_MANIFEST

/** Filename types for each folder */
export type CarouselFilename = keyof (typeof IMAGE_MANIFEST)['carousel']
