/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: npm run images:generate
 * Source: public/images/
 */

/** All image folders and their filenames (without extension) */
export const IMAGE_FOLDERS = {
  carousel: ['abu-dhabi-1', 'abu-dhabi-2'],
} as const

/** Available image folder names */
export type ImageFolder = keyof typeof IMAGE_FOLDERS

/** Filename types for each folder */
export type CarouselFilename = (typeof IMAGE_FOLDERS)['carousel'][number]

