/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: npm run images:generate
 * Source: assets/images/
 * Output: public/images/
 */

/** Available responsive image widths */
export const IMAGE_WIDTHS = [640, 1024, 1280, 1920] as const
export type ImageWidth = (typeof IMAGE_WIDTHS)[number]

/** All image folders and their base filenames (without size suffix or extension) */
export const IMAGE_FOLDERS = {
  carousel: ['abu-dhabi-1', 'abu-dhabi-2'],
} as const

/** Available image folder names */
export type ImageFolder = keyof typeof IMAGE_FOLDERS

/** Filename types for each folder */
export type CarouselFilename = (typeof IMAGE_FOLDERS)['carousel'][number]
