/**
 * Image Generator
 *
 * This script:
 * 1. Auto-discovers all subfolders in public/images/
 * 2. Generates optimized WebP versions of all source images
 * 3. Creates a TypeScript manifest with filenames and types for each folder
 *
 * Run with: npm run images:generate
 */

import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { basename, extname, join } from 'node:path'
import sharp from 'sharp'

const IMAGES_DIR = 'public/images'
const SOURCE_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.avif', '.tiff']
const OUTPUT_EXTENSION = '.webp'
const MANIFEST_PATH = 'src/lib/images/manifest.generated.ts'

// WebP quality settings
const WEBP_OPTIONS: sharp.WebpOptions = {
  quality: 80,
  effort: 6, // Higher = smaller file, slower encode (0-6)
}

// Folders to ignore (not image folders)
const IGNORED_FOLDERS = ['admin']

interface FolderResult {
  name: string
  filenames: Array<string>
}

async function main() {
  console.log('🖼️  Image Generator\n')

  // Ensure images directory exists
  if (!existsSync(IMAGES_DIR)) {
    mkdirSync(IMAGES_DIR, { recursive: true })
    console.log(`📁 Created ${IMAGES_DIR}/`)
  }

  // Find all subfolders
  const entries = readdirSync(IMAGES_DIR)
  const subfolders = entries.filter((entry) => {
    const fullPath = join(IMAGES_DIR, entry)
    return (
      statSync(fullPath).isDirectory() &&
      !IGNORED_FOLDERS.includes(entry) &&
      !entry.startsWith('.')
    )
  })

  if (subfolders.length === 0) {
    console.log(`⚠️  No image subfolders found in ${IMAGES_DIR}/`)
    console.log('   Create folders like: carousel/, gallery/, sponsors/')
    return
  }

  console.log(`Found ${subfolders.length} image folder(s): ${subfolders.join(', ')}\n`)

  // Process each folder
  const results: Array<FolderResult> = []

  for (const folder of subfolders) {
    const folderPath = join(IMAGES_DIR, folder)
    const folderResult = await processFolder(folder, folderPath)
    if (folderResult.filenames.length > 0) {
      results.push(folderResult)
    }
  }

  // Generate TypeScript manifest
  const manifest = generateManifest(results)
  writeFileSync(MANIFEST_PATH, manifest)
  console.log(`\n📝 Generated ${MANIFEST_PATH}`)

  console.log('\n✨ Done!')

  if (results.length > 0) {
    console.log('\n💡 If you added new images, update ALT_TEXTS in src/lib/images/alt-texts.ts')
  }
}

async function processFolder(
  folderName: string,
  folderPath: string,
): Promise<FolderResult> {
  console.log(`📂 ${folderName}/`)

  // Find source images (non-webp)
  const allFiles = readdirSync(folderPath)
  const sourceFiles = allFiles.filter((file) => {
    const ext = extname(file).toLowerCase()
    return SOURCE_EXTENSIONS.includes(ext)
  })

  if (sourceFiles.length === 0) {
    console.log(`   ⚠️  No source images found`)
    return { name: folderName, filenames: [] }
  }

  const filenames: Array<string> = []

  for (const sourceFile of sourceFiles) {
    const sourcePath = join(folderPath, sourceFile)
    const filenameWithoutExt = basename(sourceFile, extname(sourceFile))
    const outputFile = `${filenameWithoutExt}${OUTPUT_EXTENSION}`
    const outputPath = join(folderPath, outputFile)

    filenames.push(filenameWithoutExt)

    try {
      const { width, height } = await sharp(sourcePath).metadata()
      const { size } = await sharp(sourcePath).webp(WEBP_OPTIONS).toFile(outputPath)

      console.log(
        `   ✅ ${sourceFile} → ${outputFile} (${width}×${height}, ${Math.round(size / 1024)}KB)`,
      )
    } catch (error) {
      console.error(`   ❌ Failed to process ${sourceFile}:`, error)
    }
  }

  // Sort filenames for consistent output
  filenames.sort()

  return { name: folderName, filenames }
}

function toPascalCase(str: string): string {
  return str
    .split(/[-_]/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('')
}

function generateManifest(results: Array<FolderResult>): string {
  // Sort results by folder name
  results.sort((a, b) => a.name.localeCompare(b.name))

  // Build IMAGE_FOLDERS object
  const foldersEntries = results
    .map((r) => {
      const filenames = r.filenames.map((f) => `'${f}'`).join(', ')
      return `  ${r.name}: [${filenames}]`
    })
    .join(',\n')

  // Build type exports for each folder
  const typeExports = results
    .map((r) => {
      const typeName = `${toPascalCase(r.name)}Filename`
      return `export type ${typeName} = (typeof IMAGE_FOLDERS)['${r.name}'][number]`
    })
    .join('\n')

  return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: npm run images:generate
 * Source: ${IMAGES_DIR}/
 */

/** All image folders and their filenames (without extension) */
export const IMAGE_FOLDERS = {
${foldersEntries},
} as const

/** Available image folder names */
export type ImageFolder = keyof typeof IMAGE_FOLDERS

/** Filename types for each folder */
${typeExports}
`
}

main().catch(console.error)

