/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OrganizerRouteImport } from './routes/organizer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GalleriRouteImport } from './routes/galleri'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as OrganizerRegistrationsRouteImport } from './routes/organizer_.registrations'
import { Route as OrganizerEventsRouteImport } from './routes/organizer_.events'
import { Route as InfoTipsRouteImport } from './routes/info.tips'
import { Route as InfoResourcesRouteImport } from './routes/info.resources'
import { Route as InfoPrizesRouteImport } from './routes/info.prizes'
import { Route as InfoMaterialsRouteImport } from './routes/info.materials'
import { Route as InfoDateRouteImport } from './routes/info.date'
import { Route as InfoCostRouteImport } from './routes/info.cost'
import { Route as GalleriYearRouteImport } from './routes/galleri.$year'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo.tanstack-query'
import { Route as DemoFormRouteImport } from './routes/demo.form'
import { Route as DashboardTeamIdRouteImport } from './routes/dashboard_.$teamId'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo.start.server-funcs'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerRoute = OrganizerRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleriRoute = GalleriRouteImport.update({
  id: '/galleri',
  path: '/galleri',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerRegistrationsRoute = OrganizerRegistrationsRouteImport.update({
  id: '/organizer_/registrations',
  path: '/organizer/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerEventsRoute = OrganizerEventsRouteImport.update({
  id: '/organizer_/events',
  path: '/organizer/events',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoTipsRoute = InfoTipsRouteImport.update({
  id: '/info/tips',
  path: '/info/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoResourcesRoute = InfoResourcesRouteImport.update({
  id: '/info/resources',
  path: '/info/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoPrizesRoute = InfoPrizesRouteImport.update({
  id: '/info/prizes',
  path: '/info/prizes',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoMaterialsRoute = InfoMaterialsRouteImport.update({
  id: '/info/materials',
  path: '/info/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoDateRoute = InfoDateRouteImport.update({
  id: '/info/date',
  path: '/info/date',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoCostRoute = InfoCostRouteImport.update({
  id: '/info/cost',
  path: '/info/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleriYearRoute = GalleriYearRouteImport.update({
  id: '/$year',
  path: '/$year',
  getParentRoute: () => GalleriRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormRoute = DemoFormRouteImport.update({
  id: '/demo/form',
  path: '/demo/form',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeamIdRoute = DashboardTeamIdRouteImport.update({
  id: '/dashboard_/$teamId',
  path: '/dashboard/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/galleri': typeof GalleriRouteWithChildren
  '/login': typeof LoginRoute
  '/organizer': typeof OrganizerRoute
  '/signup': typeof SignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/$teamId': typeof DashboardTeamIdRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/galleri/$year': typeof GalleriYearRoute
  '/info/cost': typeof InfoCostRoute
  '/info/date': typeof InfoDateRoute
  '/info/materials': typeof InfoMaterialsRoute
  '/info/prizes': typeof InfoPrizesRoute
  '/info/resources': typeof InfoResourcesRoute
  '/info/tips': typeof InfoTipsRoute
  '/organizer/events': typeof OrganizerEventsRoute
  '/organizer/registrations': typeof OrganizerRegistrationsRoute
  '/blog/': typeof BlogIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/galleri': typeof GalleriRouteWithChildren
  '/login': typeof LoginRoute
  '/organizer': typeof OrganizerRoute
  '/signup': typeof SignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/$teamId': typeof DashboardTeamIdRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/galleri/$year': typeof GalleriYearRoute
  '/info/cost': typeof InfoCostRoute
  '/info/date': typeof InfoDateRoute
  '/info/materials': typeof InfoMaterialsRoute
  '/info/prizes': typeof InfoPrizesRoute
  '/info/resources': typeof InfoResourcesRoute
  '/info/tips': typeof InfoTipsRoute
  '/organizer/events': typeof OrganizerEventsRoute
  '/organizer/registrations': typeof OrganizerRegistrationsRoute
  '/blog': typeof BlogIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/galleri': typeof GalleriRouteWithChildren
  '/login': typeof LoginRoute
  '/organizer': typeof OrganizerRoute
  '/signup': typeof SignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard_/$teamId': typeof DashboardTeamIdRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/galleri/$year': typeof GalleriYearRoute
  '/info/cost': typeof InfoCostRoute
  '/info/date': typeof InfoDateRoute
  '/info/materials': typeof InfoMaterialsRoute
  '/info/prizes': typeof InfoPrizesRoute
  '/info/resources': typeof InfoResourcesRoute
  '/info/tips': typeof InfoTipsRoute
  '/organizer_/events': typeof OrganizerEventsRoute
  '/organizer_/registrations': typeof OrganizerRegistrationsRoute
  '/blog/': typeof BlogIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/galleri'
    | '/login'
    | '/organizer'
    | '/signup'
    | '/blog/$slug'
    | '/dashboard/$teamId'
    | '/demo/form'
    | '/demo/tanstack-query'
    | '/galleri/$year'
    | '/info/cost'
    | '/info/date'
    | '/info/materials'
    | '/info/prizes'
    | '/info/resources'
    | '/info/tips'
    | '/organizer/events'
    | '/organizer/registrations'
    | '/blog/'
    | '/api/auth/$'
    | '/demo/start/server-funcs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/galleri'
    | '/login'
    | '/organizer'
    | '/signup'
    | '/blog/$slug'
    | '/dashboard/$teamId'
    | '/demo/form'
    | '/demo/tanstack-query'
    | '/galleri/$year'
    | '/info/cost'
    | '/info/date'
    | '/info/materials'
    | '/info/prizes'
    | '/info/resources'
    | '/info/tips'
    | '/organizer/events'
    | '/organizer/registrations'
    | '/blog'
    | '/api/auth/$'
    | '/demo/start/server-funcs'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/galleri'
    | '/login'
    | '/organizer'
    | '/signup'
    | '/blog/$slug'
    | '/dashboard_/$teamId'
    | '/demo/form'
    | '/demo/tanstack-query'
    | '/galleri/$year'
    | '/info/cost'
    | '/info/date'
    | '/info/materials'
    | '/info/prizes'
    | '/info/resources'
    | '/info/tips'
    | '/organizer_/events'
    | '/organizer_/registrations'
    | '/blog/'
    | '/api/auth/$'
    | '/demo/start/server-funcs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  GalleriRoute: typeof GalleriRouteWithChildren
  LoginRoute: typeof LoginRoute
  OrganizerRoute: typeof OrganizerRoute
  SignupRoute: typeof SignupRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DashboardTeamIdRoute: typeof DashboardTeamIdRoute
  DemoFormRoute: typeof DemoFormRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  InfoCostRoute: typeof InfoCostRoute
  InfoDateRoute: typeof InfoDateRoute
  InfoMaterialsRoute: typeof InfoMaterialsRoute
  InfoPrizesRoute: typeof InfoPrizesRoute
  InfoResourcesRoute: typeof InfoResourcesRoute
  InfoTipsRoute: typeof InfoTipsRoute
  OrganizerEventsRoute: typeof OrganizerEventsRoute
  OrganizerRegistrationsRoute: typeof OrganizerRegistrationsRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer': {
      id: '/organizer'
      path: '/organizer'
      fullPath: '/organizer'
      preLoaderRoute: typeof OrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galleri': {
      id: '/galleri'
      path: '/galleri'
      fullPath: '/galleri'
      preLoaderRoute: typeof GalleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer_/registrations': {
      id: '/organizer_/registrations'
      path: '/organizer/registrations'
      fullPath: '/organizer/registrations'
      preLoaderRoute: typeof OrganizerRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer_/events': {
      id: '/organizer_/events'
      path: '/organizer/events'
      fullPath: '/organizer/events'
      preLoaderRoute: typeof OrganizerEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/tips': {
      id: '/info/tips'
      path: '/info/tips'
      fullPath: '/info/tips'
      preLoaderRoute: typeof InfoTipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/resources': {
      id: '/info/resources'
      path: '/info/resources'
      fullPath: '/info/resources'
      preLoaderRoute: typeof InfoResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/prizes': {
      id: '/info/prizes'
      path: '/info/prizes'
      fullPath: '/info/prizes'
      preLoaderRoute: typeof InfoPrizesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/materials': {
      id: '/info/materials'
      path: '/info/materials'
      fullPath: '/info/materials'
      preLoaderRoute: typeof InfoMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/date': {
      id: '/info/date'
      path: '/info/date'
      fullPath: '/info/date'
      preLoaderRoute: typeof InfoDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/cost': {
      id: '/info/cost'
      path: '/info/cost'
      fullPath: '/info/cost'
      preLoaderRoute: typeof InfoCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galleri/$year': {
      id: '/galleri/$year'
      path: '/$year'
      fullPath: '/galleri/$year'
      preLoaderRoute: typeof GalleriYearRouteImport
      parentRoute: typeof GalleriRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form': {
      id: '/demo/form'
      path: '/demo/form'
      fullPath: '/demo/form'
      preLoaderRoute: typeof DemoFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/$teamId': {
      id: '/dashboard_/$teamId'
      path: '/dashboard/$teamId'
      fullPath: '/dashboard/$teamId'
      preLoaderRoute: typeof DashboardTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GalleriRouteChildren {
  GalleriYearRoute: typeof GalleriYearRoute
}

const GalleriRouteChildren: GalleriRouteChildren = {
  GalleriYearRoute: GalleriYearRoute,
}

const GalleriRouteWithChildren =
  GalleriRoute._addFileChildren(GalleriRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  GalleriRoute: GalleriRouteWithChildren,
  LoginRoute: LoginRoute,
  OrganizerRoute: OrganizerRoute,
  SignupRoute: SignupRoute,
  BlogSlugRoute: BlogSlugRoute,
  DashboardTeamIdRoute: DashboardTeamIdRoute,
  DemoFormRoute: DemoFormRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  InfoCostRoute: InfoCostRoute,
  InfoDateRoute: InfoDateRoute,
  InfoMaterialsRoute: InfoMaterialsRoute,
  InfoPrizesRoute: InfoPrizesRoute,
  InfoResourcesRoute: InfoResourcesRoute,
  InfoTipsRoute: InfoTipsRoute,
  OrganizerEventsRoute: OrganizerEventsRoute,
  OrganizerRegistrationsRoute: OrganizerRegistrationsRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
