/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as InfoTipsRouteImport } from './routes/info.tips'
import { Route as InfoResourcesRouteImport } from './routes/info.resources'
import { Route as InfoPrizesRouteImport } from './routes/info.prizes'
import { Route as InfoMaterialsRouteImport } from './routes/info.materials'
import { Route as InfoDateRouteImport } from './routes/info.date'
import { Route as InfoCostRouteImport } from './routes/info.cost'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo.tanstack-query'
import { Route as DemoFormRouteImport } from './routes/demo.form'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo.start.server-funcs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoTipsRoute = InfoTipsRouteImport.update({
  id: '/info/tips',
  path: '/info/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoResourcesRoute = InfoResourcesRouteImport.update({
  id: '/info/resources',
  path: '/info/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoPrizesRoute = InfoPrizesRouteImport.update({
  id: '/info/prizes',
  path: '/info/prizes',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoMaterialsRoute = InfoMaterialsRouteImport.update({
  id: '/info/materials',
  path: '/info/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoDateRoute = InfoDateRouteImport.update({
  id: '/info/date',
  path: '/info/date',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoCostRoute = InfoCostRouteImport.update({
  id: '/info/cost',
  path: '/info/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormRoute = DemoFormRouteImport.update({
  id: '/demo/form',
  path: '/demo/form',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/info/cost': typeof InfoCostRoute
  '/info/date': typeof InfoDateRoute
  '/info/materials': typeof InfoMaterialsRoute
  '/info/prizes': typeof InfoPrizesRoute
  '/info/resources': typeof InfoResourcesRoute
  '/info/tips': typeof InfoTipsRoute
  '/blog': typeof BlogIndexRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/info/cost': typeof InfoCostRoute
  '/info/date': typeof InfoDateRoute
  '/info/materials': typeof InfoMaterialsRoute
  '/info/prizes': typeof InfoPrizesRoute
  '/info/resources': typeof InfoResourcesRoute
  '/info/tips': typeof InfoTipsRoute
  '/blog': typeof BlogIndexRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/form': typeof DemoFormRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/info/cost': typeof InfoCostRoute
  '/info/date': typeof InfoDateRoute
  '/info/materials': typeof InfoMaterialsRoute
  '/info/prizes': typeof InfoPrizesRoute
  '/info/resources': typeof InfoResourcesRoute
  '/info/tips': typeof InfoTipsRoute
  '/blog/': typeof BlogIndexRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog/$slug'
    | '/demo/form'
    | '/demo/tanstack-query'
    | '/info/cost'
    | '/info/date'
    | '/info/materials'
    | '/info/prizes'
    | '/info/resources'
    | '/info/tips'
    | '/blog'
    | '/demo/start/server-funcs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog/$slug'
    | '/demo/form'
    | '/demo/tanstack-query'
    | '/info/cost'
    | '/info/date'
    | '/info/materials'
    | '/info/prizes'
    | '/info/resources'
    | '/info/tips'
    | '/blog'
    | '/demo/start/server-funcs'
  id:
    | '__root__'
    | '/'
    | '/blog/$slug'
    | '/demo/form'
    | '/demo/tanstack-query'
    | '/info/cost'
    | '/info/date'
    | '/info/materials'
    | '/info/prizes'
    | '/info/resources'
    | '/info/tips'
    | '/blog/'
    | '/demo/start/server-funcs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DemoFormRoute: typeof DemoFormRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  InfoCostRoute: typeof InfoCostRoute
  InfoDateRoute: typeof InfoDateRoute
  InfoMaterialsRoute: typeof InfoMaterialsRoute
  InfoPrizesRoute: typeof InfoPrizesRoute
  InfoResourcesRoute: typeof InfoResourcesRoute
  InfoTipsRoute: typeof InfoTipsRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/tips': {
      id: '/info/tips'
      path: '/info/tips'
      fullPath: '/info/tips'
      preLoaderRoute: typeof InfoTipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/resources': {
      id: '/info/resources'
      path: '/info/resources'
      fullPath: '/info/resources'
      preLoaderRoute: typeof InfoResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/prizes': {
      id: '/info/prizes'
      path: '/info/prizes'
      fullPath: '/info/prizes'
      preLoaderRoute: typeof InfoPrizesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/materials': {
      id: '/info/materials'
      path: '/info/materials'
      fullPath: '/info/materials'
      preLoaderRoute: typeof InfoMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/date': {
      id: '/info/date'
      path: '/info/date'
      fullPath: '/info/date'
      preLoaderRoute: typeof InfoDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/cost': {
      id: '/info/cost'
      path: '/info/cost'
      fullPath: '/info/cost'
      preLoaderRoute: typeof InfoCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form': {
      id: '/demo/form'
      path: '/demo/form'
      fullPath: '/demo/form'
      preLoaderRoute: typeof DemoFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogSlugRoute: BlogSlugRoute,
  DemoFormRoute: DemoFormRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  InfoCostRoute: InfoCostRoute,
  InfoDateRoute: InfoDateRoute,
  InfoMaterialsRoute: InfoMaterialsRoute,
  InfoPrizesRoute: InfoPrizesRoute,
  InfoResourcesRoute: InfoResourcesRoute,
  InfoTipsRoute: InfoTipsRoute,
  BlogIndexRoute: BlogIndexRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
