/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as OrganizerRouteImport } from './routes/organizer'
import { Route as OrderATrackRouteImport } from './routes/order-a-track'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as OrganizerRegistrationsRouteImport } from './routes/organizer_.registrations'
import { Route as OrganizerRecoveryRouteImport } from './routes/organizer_.recovery'
import { Route as OrganizerEventsRouteImport } from './routes/organizer_.events'
import { Route as InfoTipsRouteImport } from './routes/info.tips'
import { Route as InfoRulesRouteImport } from './routes/info.rules'
import { Route as InfoResourcesRouteImport } from './routes/info.resources'
import { Route as InfoPrizesRouteImport } from './routes/info.prizes'
import { Route as InfoMaterialsRouteImport } from './routes/info.materials'
import { Route as InfoDateRouteImport } from './routes/info.date'
import { Route as InfoCostRouteImport } from './routes/info.cost'
import { Route as GalleryYearRouteImport } from './routes/gallery_.$year'
import { Route as DashboardTeamIdRouteImport } from './routes/dashboard_.$teamId'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as GalleryYearSlugRouteImport } from './routes/gallery_.$year_.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as GalleryYearEventEventRouteImport } from './routes/gallery_.$year_.event.$event'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerRoute = OrganizerRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderATrackRoute = OrderATrackRouteImport.update({
  id: '/order-a-track',
  path: '/order-a-track',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerRegistrationsRoute = OrganizerRegistrationsRouteImport.update({
  id: '/organizer_/registrations',
  path: '/organizer/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerRecoveryRoute = OrganizerRecoveryRouteImport.update({
  id: '/organizer_/recovery',
  path: '/organizer/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerEventsRoute = OrganizerEventsRouteImport.update({
  id: '/organizer_/events',
  path: '/organizer/events',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoTipsRoute = InfoTipsRouteImport.update({
  id: '/info/tips',
  path: '/info/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRulesRoute = InfoRulesRouteImport.update({
  id: '/info/rules',
  path: '/info/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoResourcesRoute = InfoResourcesRouteImport.update({
  id: '/info/resources',
  path: '/info/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoPrizesRoute = InfoPrizesRouteImport.update({
  id: '/info/prizes',
  path: '/info/prizes',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoMaterialsRoute = InfoMaterialsRouteImport.update({
  id: '/info/materials',
  path: '/info/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoDateRoute = InfoDateRouteImport.update({
  id: '/info/date',
  path: '/info/date',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoCostRoute = InfoCostRouteImport.update({
  id: '/info/cost',
  path: '/info/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryYearRoute = GalleryYearRouteImport.update({
  id: '/gallery_/$year',
  path: '/gallery/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeamIdRoute = DashboardTeamIdRouteImport.update({
  id: '/dashboard_/$teamId',
  path: '/dashboard/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryYearSlugRoute = GalleryYearSlugRouteImport.update({
  id: '/gallery_/$year_/$slug',
  path: '/gallery/$year/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryYearEventEventRoute = GalleryYearEventEventRouteImport.update({
  id: '/gallery_/$year_/event/$event',
  path: '/gallery/$year/event/$event',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/order-a-track': typeof OrderATrackRoute
  '/organizer': typeof OrganizerRoute
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/$teamId': typeof DashboardTeamIdRoute
  '/gallery/$year': typeof GalleryYearRoute
  '/info/cost': typeof InfoCostRoute
  '/info/date': typeof InfoDateRoute
  '/info/materials': typeof InfoMaterialsRoute
  '/info/prizes': typeof InfoPrizesRoute
  '/info/resources': typeof InfoResourcesRoute
  '/info/rules': typeof InfoRulesRoute
  '/info/tips': typeof InfoTipsRoute
  '/organizer/events': typeof OrganizerEventsRoute
  '/organizer/recovery': typeof OrganizerRecoveryRoute
  '/organizer/registrations': typeof OrganizerRegistrationsRoute
  '/blog/': typeof BlogIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/gallery/$year/$slug': typeof GalleryYearSlugRoute
  '/gallery/$year/event/$event': typeof GalleryYearEventEventRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/order-a-track': typeof OrderATrackRoute
  '/organizer': typeof OrganizerRoute
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/$teamId': typeof DashboardTeamIdRoute
  '/gallery/$year': typeof GalleryYearRoute
  '/info/cost': typeof InfoCostRoute
  '/info/date': typeof InfoDateRoute
  '/info/materials': typeof InfoMaterialsRoute
  '/info/prizes': typeof InfoPrizesRoute
  '/info/resources': typeof InfoResourcesRoute
  '/info/rules': typeof InfoRulesRoute
  '/info/tips': typeof InfoTipsRoute
  '/organizer/events': typeof OrganizerEventsRoute
  '/organizer/recovery': typeof OrganizerRecoveryRoute
  '/organizer/registrations': typeof OrganizerRegistrationsRoute
  '/blog': typeof BlogIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/gallery/$year/$slug': typeof GalleryYearSlugRoute
  '/gallery/$year/event/$event': typeof GalleryYearEventEventRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/order-a-track': typeof OrderATrackRoute
  '/organizer': typeof OrganizerRoute
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard_/$teamId': typeof DashboardTeamIdRoute
  '/gallery_/$year': typeof GalleryYearRoute
  '/info/cost': typeof InfoCostRoute
  '/info/date': typeof InfoDateRoute
  '/info/materials': typeof InfoMaterialsRoute
  '/info/prizes': typeof InfoPrizesRoute
  '/info/resources': typeof InfoResourcesRoute
  '/info/rules': typeof InfoRulesRoute
  '/info/tips': typeof InfoTipsRoute
  '/organizer_/events': typeof OrganizerEventsRoute
  '/organizer_/recovery': typeof OrganizerRecoveryRoute
  '/organizer_/registrations': typeof OrganizerRegistrationsRoute
  '/blog/': typeof BlogIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/gallery_/$year_/$slug': typeof GalleryYearSlugRoute
  '/gallery_/$year_/event/$event': typeof GalleryYearEventEventRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/dashboard'
    | '/gallery'
    | '/login'
    | '/order-a-track'
    | '/organizer'
    | '/recover'
    | '/signup'
    | '/blog/$slug'
    | '/dashboard/$teamId'
    | '/gallery/$year'
    | '/info/cost'
    | '/info/date'
    | '/info/materials'
    | '/info/prizes'
    | '/info/resources'
    | '/info/rules'
    | '/info/tips'
    | '/organizer/events'
    | '/organizer/recovery'
    | '/organizer/registrations'
    | '/blog/'
    | '/api/auth/$'
    | '/gallery/$year/$slug'
    | '/gallery/$year/event/$event'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/dashboard'
    | '/gallery'
    | '/login'
    | '/order-a-track'
    | '/organizer'
    | '/recover'
    | '/signup'
    | '/blog/$slug'
    | '/dashboard/$teamId'
    | '/gallery/$year'
    | '/info/cost'
    | '/info/date'
    | '/info/materials'
    | '/info/prizes'
    | '/info/resources'
    | '/info/rules'
    | '/info/tips'
    | '/organizer/events'
    | '/organizer/recovery'
    | '/organizer/registrations'
    | '/blog'
    | '/api/auth/$'
    | '/gallery/$year/$slug'
    | '/gallery/$year/event/$event'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/dashboard'
    | '/gallery'
    | '/login'
    | '/order-a-track'
    | '/organizer'
    | '/recover'
    | '/signup'
    | '/blog/$slug'
    | '/dashboard_/$teamId'
    | '/gallery_/$year'
    | '/info/cost'
    | '/info/date'
    | '/info/materials'
    | '/info/prizes'
    | '/info/resources'
    | '/info/rules'
    | '/info/tips'
    | '/organizer_/events'
    | '/organizer_/recovery'
    | '/organizer_/registrations'
    | '/blog/'
    | '/api/auth/$'
    | '/gallery_/$year_/$slug'
    | '/gallery_/$year_/event/$event'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  OrderATrackRoute: typeof OrderATrackRoute
  OrganizerRoute: typeof OrganizerRoute
  RecoverRoute: typeof RecoverRoute
  SignupRoute: typeof SignupRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DashboardTeamIdRoute: typeof DashboardTeamIdRoute
  GalleryYearRoute: typeof GalleryYearRoute
  InfoCostRoute: typeof InfoCostRoute
  InfoDateRoute: typeof InfoDateRoute
  InfoMaterialsRoute: typeof InfoMaterialsRoute
  InfoPrizesRoute: typeof InfoPrizesRoute
  InfoResourcesRoute: typeof InfoResourcesRoute
  InfoRulesRoute: typeof InfoRulesRoute
  InfoTipsRoute: typeof InfoTipsRoute
  OrganizerEventsRoute: typeof OrganizerEventsRoute
  OrganizerRecoveryRoute: typeof OrganizerRecoveryRoute
  OrganizerRegistrationsRoute: typeof OrganizerRegistrationsRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  GalleryYearSlugRoute: typeof GalleryYearSlugRoute
  GalleryYearEventEventRoute: typeof GalleryYearEventEventRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer': {
      id: '/organizer'
      path: '/organizer'
      fullPath: '/organizer'
      preLoaderRoute: typeof OrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-a-track': {
      id: '/order-a-track'
      path: '/order-a-track'
      fullPath: '/order-a-track'
      preLoaderRoute: typeof OrderATrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer_/registrations': {
      id: '/organizer_/registrations'
      path: '/organizer/registrations'
      fullPath: '/organizer/registrations'
      preLoaderRoute: typeof OrganizerRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer_/recovery': {
      id: '/organizer_/recovery'
      path: '/organizer/recovery'
      fullPath: '/organizer/recovery'
      preLoaderRoute: typeof OrganizerRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer_/events': {
      id: '/organizer_/events'
      path: '/organizer/events'
      fullPath: '/organizer/events'
      preLoaderRoute: typeof OrganizerEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/tips': {
      id: '/info/tips'
      path: '/info/tips'
      fullPath: '/info/tips'
      preLoaderRoute: typeof InfoTipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/rules': {
      id: '/info/rules'
      path: '/info/rules'
      fullPath: '/info/rules'
      preLoaderRoute: typeof InfoRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/resources': {
      id: '/info/resources'
      path: '/info/resources'
      fullPath: '/info/resources'
      preLoaderRoute: typeof InfoResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/prizes': {
      id: '/info/prizes'
      path: '/info/prizes'
      fullPath: '/info/prizes'
      preLoaderRoute: typeof InfoPrizesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/materials': {
      id: '/info/materials'
      path: '/info/materials'
      fullPath: '/info/materials'
      preLoaderRoute: typeof InfoMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/date': {
      id: '/info/date'
      path: '/info/date'
      fullPath: '/info/date'
      preLoaderRoute: typeof InfoDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/cost': {
      id: '/info/cost'
      path: '/info/cost'
      fullPath: '/info/cost'
      preLoaderRoute: typeof InfoCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery_/$year': {
      id: '/gallery_/$year'
      path: '/gallery/$year'
      fullPath: '/gallery/$year'
      preLoaderRoute: typeof GalleryYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/$teamId': {
      id: '/dashboard_/$teamId'
      path: '/dashboard/$teamId'
      fullPath: '/dashboard/$teamId'
      preLoaderRoute: typeof DashboardTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery_/$year_/$slug': {
      id: '/gallery_/$year_/$slug'
      path: '/gallery/$year/$slug'
      fullPath: '/gallery/$year/$slug'
      preLoaderRoute: typeof GalleryYearSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery_/$year_/event/$event': {
      id: '/gallery_/$year_/event/$event'
      path: '/gallery/$year/event/$event'
      fullPath: '/gallery/$year/event/$event'
      preLoaderRoute: typeof GalleryYearEventEventRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  OrderATrackRoute: OrderATrackRoute,
  OrganizerRoute: OrganizerRoute,
  RecoverRoute: RecoverRoute,
  SignupRoute: SignupRoute,
  BlogSlugRoute: BlogSlugRoute,
  DashboardTeamIdRoute: DashboardTeamIdRoute,
  GalleryYearRoute: GalleryYearRoute,
  InfoCostRoute: InfoCostRoute,
  InfoDateRoute: InfoDateRoute,
  InfoMaterialsRoute: InfoMaterialsRoute,
  InfoPrizesRoute: InfoPrizesRoute,
  InfoResourcesRoute: InfoResourcesRoute,
  InfoRulesRoute: InfoRulesRoute,
  InfoTipsRoute: InfoTipsRoute,
  OrganizerEventsRoute: OrganizerEventsRoute,
  OrganizerRecoveryRoute: OrganizerRecoveryRoute,
  OrganizerRegistrationsRoute: OrganizerRegistrationsRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  GalleryYearSlugRoute: GalleryYearSlugRoute,
  GalleryYearEventEventRoute: GalleryYearEventEventRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
